//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int S_id { get; set; }

        [Required]
        public string S_Name { get; set; }
        public Nullable<int> S_Age { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
